=== GBT/Mbean-Monitor/Mbean-Monitor/src/main/config/jbossreportserver.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by PASCAL PUJO (SEMA) -->
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by Gilles Bardouillet (SchlumbergerSema) -->
<!--W3C Schema generated by XML Spy v4.1 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="ServerParam">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="mbean" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="host" type="xs:string" use="optional" default="localhost"/>
			<xs:attribute name="port" type="xs:short" use="optional" default="1099"/>
			<xs:attribute name="genereTo" type="xs:anyURI" use="required"/>
			<xs:attribute name="extension" type="xs:string" use="optional" default="csv"/>
			<xs:attribute name="MaxFileSize" type="xs:string" use="optional" default="1024KB"/>
			<xs:attribute name="MaxBackupIndex" type="xs:int" use="optional" default="10"/>
			<xs:attribute name="delay" type="xs:int" use="optional" default="30"/>
			<xs:attribute name="NbThreads" type="xs:int" use="optional" default="10"/>
			<xs:attribute name="separateur" type="xs:string" use="optional" default=";"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="attribute">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="messagecounter" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="stat" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="list" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="optional" default="description"/>
			<xs:attribute name="regexpr" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="element">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="optional">
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="methodStat">
		<xs:complexType>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Count"/>
						<xs:enumeration value="Min.Time"/>
						<xs:enumeration value="Moy.Time"/>
						<xs:enumeration value="Max.Time"/>
						<xs:enumeration value="Total.Time"/>
						<xs:enumeration value="low"/>
						<xs:enumeration value="high"/>
						<xs:enumeration value="current"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="element" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="stat">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="methodStat" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="messagecounter">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="mbean">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="attribute" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="domain" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="jboss"/>
						<xs:enumeration value="jboss.cache"/>
						<xs:enumeration value="jboss.admin"/>
						<xs:enumeration value="jboss.jca"/>
						<xs:enumeration value="jboss.deployment"/>
						<xs:enumeration value="jboss.ejb"/>
						<xs:enumeration value="jboss.j2ee"/>
						<xs:enumeration value="jboss.jca"/>
						<xs:enumeration value="jboss.jdbc"/>
						<xs:enumeration value="jboss.jmx"/>
						<xs:enumeration value="jboss.management.local"/>
						<xs:enumeration value="jboss.mq"/>
						<xs:enumeration value="jboss.mq.destination"/>
						<xs:enumeration value="jboss.rmi"/>
						<xs:enumeration value="jboss.scripts"/>
						<xs:enumeration value="jboss.security"/>
						<xs:enumeration value="jboss.system"/>
						<xs:enumeration value="jboss.web"/>
						<xs:enumeration value="jboss.messaging"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="filename" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== GBT/Mbean-Monitor/Mbean-Monitor/src/main/config/jbossreportdefault.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Paramétrage par défaut de l'outil de capture des MBeans JBOSS-->
<ServerParam host="localhost" port="1099" genereTo="/tmp/JbossReport" extension="csv" MaxFileSize="14096KB" MaxBackupIndex="10" delay="30" separateur=";" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="jbossreportserver.xsd">

<!-- Domain Name:jboss.system ServerInfo -->
        <mbean name="type=ServerInfo" domain="jboss.system" filename="jboss-Memory">
                <attribute name="FreeMemory"/>
                <attribute name="MaxMemory"/>
                <attribute name="TotalMemory"/>
        </mbean>
        <mbean name="type=ServerInfo" domain="jboss.system" filename="jboss-Threads">
                <attribute name="ActiveThreadCount"/>
        </mbean>

<!-- Domain Name:jboss.jca  JDBC Pools -->
        <mbean name="name=DefaultDS,service=ManagedConnectionPool" domain="jboss.jca" filename="jdbc-DefaultDS">
                <attribute name="AvailableConnectionCount"/>
                <attribute name="MaxConnectionsInUseCount"/>
                <attribute name="InUseConnectionCount"/>
                <attribute name="ConnectionCreatedCount"/>
                <attribute name="ConnectionDestroyedCount"/>
        </mbean>

<!-- Domain Name:jboss.web  Connectors Pools -->
        <mbean name="name=http-0.0.0.0-8080,type=ThreadPool" domain="jboss.web" filename="tomcat-Pool">
                <attribute name="currentThreadsBusy"/>
                <attribute name="currentThreadCount"/>
                <attribute name="maxThreads"/>
        </mbean>
        <mbean name="name=jk-8009,type=ThreadPool" domain="jboss.web" filename="jk-Pool">
                <attribute name="currentThreadsBusy"/>
                <attribute name="currentThreadCount"/>
                <attribute name="maxThreads"/>
        </mbean>

<!-- Domain Name:jboss.web  Webapps actives -->
        <mbean name="host=localhost,path=/web-console,type=Manager" domain="jboss.web" filename="web-Console">
                <attribute name="activeSessions"/>
        </mbean>

<!-- Domain Name:jboss.web  Sessions -->
        <mbean name="J2EEApplication=none,J2EEServer=none,j2eeType=WebModule,name=//localhost/jmx-console" domain="jboss.web" filename="web-jmx-console">
                <attribute name="state"/>
        </mbean>


</ServerParam>
